alias startmongo='cd $HOME/778336;./mongod'
alias cdhome='cd $HOME/778336'
alias cdjs='cdhome;cd client/js'
alias coffeejs='cdjs;coffee -c *.coffee'
alias cdjssource='./node_modules/mongoose/examples/express/connection-sharing/'
