// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('roles', []);

  app.factory('roles', function() {
    var roles, userRoles;
    roles = {};
    userRoles = {
      "public": 1,
      user: 2,
      admin: 4
    };
    roles.userRoles = userRoles;
    roles.accessLevels = {
      "public": userRoles["public"] | userRoles.user | userRoles.admin,
      anon: userRoles["public"],
      user: userRoles.user | userRoles.admin,
      admin: userRoles.admin
    };
    return roles;
  });

}).call(this);
